{
 "title": "Supervision Mikrotik",
 "description": "github.com/bakraw/mikrotik-grafana",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp v3",
  "snmp_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {}
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(ifName(instance=\"$instance\"))"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_name",
    "query": {
     "query": "query_result((mtxrQueueTreePackets * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_parent",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_flow",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeName) group_left(mtxrQueueTreeIndex) mtxrQueueTreeIndex{instance='$instance',}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "ip", "language": "jsonata", "name": "IP" },
      { "jsonPath": "lat", "language": "jsonata", "name": "Lat" },
      { "jsonPath": "lon", "language": "jsonata", "name": "Lon" },
      { "jsonPath": "adresse", "language": "jsonata", "name": "Adresse" },
      { "jsonPath": "statut", "language": "jsonata", "name": "Statut" }
     ],
     "method": "GET",
     "urlPath": "/"
    }
   ]
  },
  {
   "title": "SNMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total SNMP time (walk and processing)",
   "type": "stat",
   "description": "Total SNMP time scrape took (walk and processing)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Time SNMP walk/bulkwalk took",
   "type": "stat",
   "description": "Time SNMP walk/bulkwalk took",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_walk_duration_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "scrape pdus returned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_pdus_returned{instance='$instance'}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "Status device",
   "type": "stat",
   "description": "The current operational state of the device described by this row of the table. A value unknown(1) indicates that the current state of the device is unknown. running(2) indicates that the device is up and running and that no unusual error conditions are known. The warning(3) state indicates that agent has been informed of an unusual error condition by the operational software (e.g., a disk device driver) but that the device is still 'operational'. An example would be a high number of soft errors on a disk. A value of testing(4), indicates that the device is not available for use because it is in the testing state. The state of down(5) is used only when the agent has been informed that the device is not available for any use.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceStatus{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "Device Errors",
   "type": "stat",
   "description": "The number of errors detected on this device",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrDeviceErrors{instance='$instance', hrDeviceIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "System identity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysIdentity{instance='$instance'}",
     "legendFormat": "{{sysIdentity}}"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrSerialNumber{instance='$instance'}",
     "legendFormat": "{{mtxrSerialNumber}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysDescr{instance='$instance'}", "legendFormat": "{{sysDescr}}" }
   ]
  },
  {
   "title": "System date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(hrSystemDate{instance='$instance'})"
    }
   ]
  },
  {
   "title": "Board ver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrFirmwareVersion{instance='$instance'}",
     "legendFormat": "{{mtxrFirmwareVersion}}"
    }
   ]
  },
  {
   "title": "Package ver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrLicVersion{instance='$instance'}",
     "legendFormat": "{{mtxrLicVersion}}"
    }
   ]
  },
  {
   "title": "Board Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrBoardName{instance='$instance'}",
     "legendFormat": "{{mtxrBoardName}}"
    }
   ]
  },
  {
   "title": "Software ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicSoftwareId{instance='$instance'}",
     "legendFormat": "{{mtxrLicSoftwareId}}"
    }
   ]
  },
  {
   "title": "Note",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mtxrNote{instance='$instance'}", "legendFormat": " {{mtxrNote}}" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})"
    }
   ]
  },
  {
   "title": "RAM load ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "system disk load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorTemperature{instance='$instance'}/10 or mtxrHlTemperature{instance='$instance'}/10"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}",
     "legendFormat": "CPU {{hrDeviceIndex}}  load"
    },
    {
     "expr": "mtxrHlTemperature{instance='$instance'}/10",
     "legendFormat": "CPU temp"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "System disk"
    },
    {
     "expr": "mtxrHlVoltage{instance='$instance'}/10",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorFrequency{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Active Fan",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mtxrHlActiveFan{instance='$instance'}",
     "legendFormat": "{{mtxrHlActiveFan}}"
    }
   ]
  },
  {
   "title": "Wi-Fi client count",
   "type": "stat",
   "description": "Wireless registration table entry count",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrWlRtabEntryCount{instance='$instance'}"
    }
   ]
  },
  {
   "title": "License level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicLevel{instance='$instance'}",
     "legendFormat": "Lic"
    },
    {
     "expr": "mtxrLicUpgradableTo{instance='$instance'}",
     "legendFormat": "Upgradable to"
    }
   ]
  },
  {
   "title": "POE Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEStatus{instance='$instance'}"
    }
   ]
  },
  {
   "title": "POE Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEPower{instance='$instance'}",
     "legendFormat": "POE Power"
    }
   ]
  },
  {
   "title": "POE Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOECurrent{instance='$instance'}",
     "legendFormat": "POE Current"
    }
   ]
  },
  {
   "title": "POE Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrPOEVoltage{instance='$instance'}",
     "legendFormat": "POE Voltage"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "-irate(ifOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    { "expr": "ifSpeed{instance='$instance'}" },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance='$instance'}"
    },
    { "expr": "ifMtu{instance='$instance'}" },
    {
     "expr": "ifType_info{instance='$instance'}"
    },
    {
     "expr": "mtxrPOEInterfaceIndex{instance='$instance'}"
    },
    { "expr": "ifAlias{instance='$instance'}" }
   ]
  },
  {
   "title": "Tx Eth errors, etc",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(mtxrInterfaceStatsTxControl{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Control - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxDeferred{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Deferred - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxDrop{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Drop - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxExcessiveCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Excessive Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxExcessiveDeferred{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Excessive Deferred - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxFCSError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx FCS Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxFragment{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Fragment - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxJabber{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Jabber - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxLateCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Late Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxMultipleCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Multiple Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxPause{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Pause - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxPauseHonored{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Pause Honored - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxSingleCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Single Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxTooLong{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Too Long - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxTooShort{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Too Short - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxTotalCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Total Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxUnderrun{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Under run - {{ifName}}"
    }
   ]
  },
  {
   "title": "Rx Eth errors, etc",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(mtxrInterfaceStatsRxAlignError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Align Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxCarrierError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Carrier Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxControl{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Control - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxDrop{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Drop - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxFCSError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "FCS Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxFragment{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Fragment - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxJabber{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Jabber - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxLengthError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Length Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxOverflow{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Overflow - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxPause{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Pause - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxTooLong{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Too Long - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxTooShort{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Too Short - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxUnknownOp{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Unknown Op - {{ifName}}"
    }
   ]
  },
  {
   "title": "Neighbors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mtxrNeighborInterfaceID{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborIdentity{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborIpAddress{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborMacAddress{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborPlatform{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborSoftwareID{instance='$instance'}"
    },
    {
     "expr": "mtxrNeighborVersion{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Wireless",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wi-Fi Overall Tx CCQ & Noise",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(mtxrWlApOverallTxCCQ{instance='$instance'}*on(mtxrWlApIndex)group_left(mtxrWlApSsid)mtxrWlApSsid{instance='$instance'})",
     "legendFormat": "TX CCQ - {{mtxrWlApSsid}}"
    },
    {
     "expr": "(mtxrWlApNoiseFloor{instance='$instance'}*on(mtxrWlApIndex)group_left(mtxrWlApSsid)mtxrWlApSsid{instance='$instance'})",
     "legendFormat": "Noise - {{mtxrWlApSsid}}"
    }
   ]
  },
  {
   "title": "Wi-Fi Client count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(mtxrWlApAuthClientCount{instance='$instance'}*on(mtxrWlApIndex)group_left(mtxrWlApSsid)mtxrWlApSsid{instance='$instance'})",
     "legendFormat": "{{mtxrWlApSsid}}"
    },
    {
     "expr": "mtxrDHCPLeaseCount{instance='$instance'}",
     "legendFormat": "DHCP Leases"
    }
   ]
  },
  {
   "title": "Wi-Fi frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "mtxrWlApFreq{instance='$instance'}*on(mtxrWlApIndex)group_left(mtxrWlApSsid)mtxrWlApSsid{instance='$instance'}",
     "legendFormat": "{{mtxrWlApSsid}}"
    }
   ]
  },
  {
   "title": "Wi-Fi Clients",
   "type": "table",
   "description": "Wireless registration table. It is indexed by remote mac-address and local interface index.\n\nMeasured in dB, if value does not exist it is indicated with 0",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "mtxrWlRtabAddr{instance='$instance'}"
    },
    {
     "expr": "mtxrWlRtabSignalToNoise{instance='$instance'}"
    },
    {
     "expr": "mtxrWlRtabStrength{instance='$instance'}"
    },
    {
     "expr": "mtxrWlRtabTxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrWlRtabRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrWlRtabTxRate{instance='$instance'}"
    },
    {
     "expr": "mtxrWlRtabRxRate{instance='$instance'}"
    },
    {
     "expr": "mtxrWlRtabUptime{instance='$instance'}"
    }
   ]
  },
  {
   "title": "History Wi-Fi Strength",
   "type": "heatmap",
   "description": "Signal Strength: signal strength in dBm (if first ppp-client modem supports)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "mtxrWlRtabStrength{instance='$instance'}",
     "legendFormat": "{{mtxrWlRtabAddr}}"
    }
   ]
  },
  {
   "title": "History Wi-Fi Signal-to-Noise",
   "type": "heatmap",
   "description": "Measured in dB, if value does not exist it is indicated with 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "mtxrWlRtabSignalToNoise{instance='$instance'}",
     "legendFormat": "{{mtxrWlRtabAddr}}"
    }
   ]
  },
  {
   "title": "CAPsMAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CAPsMAN client count",
     "type": "stat",
     "description": "Wireless registration table entry count",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWlCMRtabEntryCount{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Remote CAP",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 3, "y": 98 },
     "targets": [
      {
       "expr": "mtxrWlCMRemoteAddress{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRemoteName{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRemoteRadios{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRemoteState{instance='$instance'}"
      }
     ]
    },
    {
     "title": "CAP interface",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 98 },
     "targets": [
      {
       "expr": "mtxrWlCMState{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRegClientCount{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMChannel{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMAuthClientCount{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabSsid{instance='$instance'}"
      }
     ]
    },
    {
     "title": "remote-cap entry count",
     "type": "stat",
     "description": "Wireless CAPSMAN remote-cap entry count",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWlCMREntryCount{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "mtxrWlCMRtabAddr{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabEapIdent{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabRxBytes{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabRxPackets{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabRxRate{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabRxStrength{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabSsid{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabTxBytes{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabTxPackets{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabTxRate{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabTxStrength{instance='$instance'}"
      },
      {
       "expr": "mtxrWlCMRtabUptime{instance='$instance'}"
      }
     ]
    }
   ]
  },
  {
   "title": "W60G",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ssid",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GSsid{instance='$instance'}",
       "legendFormat": "{{mtxrWl60GSsid}}"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GFreq{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Connected",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GConnected{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Mode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GMode{instance='$instance'}"
      }
     ]
    },
    {
     "title": "RSSI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mtxrWl60GRssi{instance='$instance'}",
       "legendFormat": "RSSI"
      }
     ]
    },
    {
     "title": "PhyRate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GPhyRate{instance='$instance'}"
      }
     ]
    },
    {
     "title": "TxSector",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GTxSector{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Signal",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GSignal{instance='$instance'}"
      }
     ]
    },
    {
     "title": "TxSectorInfo",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GTxSectorInfo{instance='$instance'}"
      }
     ]
    },
    {
     "title": "MCS (Modulation and Coding Scheme)",
     "type": "stat",
     "description": "Modulation and Coding Scheme",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GMcs{instance='$instance'}"
      }
     ]
    },
    {
     "title": "Remote MAC",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mtxrWl60GRemote{instance='$instance'}",
       "legendFormat": "{{mtxrWl60GRemote}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Modem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Modem",
   "type": "timeseries",
   "description": "Signal Strength: signal strength in dBm (if first ppp-client modem supports)\n\nModem Signal: signal EC/IO in dB (if first ppp-client modem supports)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "mtxrWirelessModemSignalStrength{instance='$instance'}",
     "legendFormat": "Signal Strength"
    },
    {
     "expr": "mtxrWirelessModemSignalECIO{instance='$instance'}",
     "legendFormat": "Modem Signal"
    }
   ]
  },
  {
   "title": "USB Power Reset",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrUSBPowerReset{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Simple Queue (In/Out/Dropped/PCQ)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Simple Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(irate(mtxrQueueSimpleBytesIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8 ",
     "legendFormat": "In - {{mtxrQueueSimpleName}}"
    },
    {
     "expr": "(irate(mtxrQueueSimpleBytesOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})*8",
     "legendFormat": "Out - {{mtxrQueueSimpleName}}"
    },
    {
     "expr": "(mtxrQueueSimplePCQQueuesIn{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})",
     "legendFormat": "PCQ In - {{mtxrQueueSimpleName}}"
    },
    {
     "expr": "(mtxrQueueSimplePCQQueuesOut{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{instance='$instance'})",
     "legendFormat": "PCQ Out - {{mtxrQueueSimpleName}}"
    }
   ]
  },
  {
   "title": "Queue $queuesimple_name",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 114 },
   "repeat": "queuesimple_name",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(irate(mtxrQueueSimpleBytesIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
     "legendFormat": "In"
    },
    {
     "expr": "(irate(mtxrQueueSimpleBytesOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})*8",
     "legendFormat": "Out"
    },
    {
     "expr": "(irate(mtxrQueueSimpleDroppedIn{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
     "legendFormat": "Dropped In"
    },
    {
     "expr": "(irate(mtxrQueueSimpleDroppedOut{instance='$instance'}[$__rate_interval])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name', instance='$instance'})",
     "legendFormat": "Dropped Out "
    },
    {
     "expr": "(mtxrQueueSimplePCQQueuesIn{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
     "legendFormat": "PCQ-In"
    },
    {
     "expr": "(mtxrQueueSimplePCQQueuesOut{instance='$instance'}*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})",
     "legendFormat": "PCQ-Out"
    }
   ]
  },
  {
   "title": "Tree Queue (Bytes/PCQ/Dropped/Packets)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Tree Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})*8",
     "legendFormat": "Bytes - {{mtxrQueueTreeName}}"
    },
    {
     "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
     "legendFormat": "PCQ - {{mtxrQueueTreeName}}"
    },
    {
     "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
     "legendFormat": "Dropped - {{mtxrQueueTreeName}}"
    },
    {
     "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{instance='$instance'})",
     "legendFormat": "Packets - {{mtxrQueueTreeName}}"
    }
   ]
  },
  {
   "title": "Tree Queue $queuetree_name / $queuetree_parent / $queuetree_flow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 121 },
   "repeat": "queuetree_name",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(irate(mtxrQueueTreeHCBytes{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})*8",
     "legendFormat": "Bytes"
    },
    {
     "expr": "(irate(mtxrQueueTreePCQQueues{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
     "legendFormat": "PCQ"
    },
    {
     "expr": "(irate(mtxrQueueTreeDropped{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
     "legendFormat": "Dropped"
    },
    {
     "expr": "(irate(mtxrQueueTreePackets{instance='$instance'}[$__rate_interval])*on(mtxrQueueTreeIndex)group_left(mtxrQueueTreeName)mtxrQueueTreeName{mtxrQueueTreeName='$queuetree_name',instance='$instance'})",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "*cast/Dascard/Errors/Unknown Protos/Queue length",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Interface \"$Interface\"",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 128 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "-irate(ifHCOutMulticastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "-irate(ifHCOutBroadcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "-irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(ifInErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(ifOutErrors{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(ifInUnknownProtos{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "-irate(ifOutQLen{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "Interfaces Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic \"$Interface\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 162 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-irate(ifOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}